import { Letter } from "../strands/models";

export const firstRiddleDateISO = '2025-01-05';

export const defaultLetterGrid: Letter[] = [
  { letter: '', location: { row: 0, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 0, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 0, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 0, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 0, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 0, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 1, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 1, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 1, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 1, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 1, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 1, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 2, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 2, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 2, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 2, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 2, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 2, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 3, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 3, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 3, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 3, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 3, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 3, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 4, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 4, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 4, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 4, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 4, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 4, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 5, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 5, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 5, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 5, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 5, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 5, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 6, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 6, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 6, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 6, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 6, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 6, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 7, col: 0 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 7, col: 1 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 7, col: 2 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 7, col: 3 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 7, col: 4 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 },
  { letter: '', location: { row: 7, col: 5 }, hintFoundDelay: 0, isGuessActive: false, isSolutionActive: false, isSuperSolutionActive: false, hintTiming: -1 }
];
