name: publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker build . \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:latest \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          docker push ghcr.io/${{ env.IMAGE_NAME }} --all-tags
