name: publish-staging

on:
  push:
    branches: ["develop"]

jobs:
  publish-staging:
    name: publish staging image
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repository
        uses: actions/checkout@v3
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build and publish
        run: |
          docker build . \
            --build-arg CONFIGURATION=staging \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:staging \
            --tag ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ghcr.io/${{ env.IMAGE_NAME }} --all-tags
